In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.4'

In [4]:
arr=np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
a=[1,2,3,4,4.5,'hello']
a

[1, 2, 3, 4, 4.5, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3', '4', '4.5', 'hello'], dtype='<U32')

In [7]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [10]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr=np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.random.rand(5)

array([0.1598435 , 0.2767247 , 0.40466495, 0.40115694, 0.42519483])

In [14]:
np.random.randn(10)

array([ 1.8499792 , -1.46265881,  0.31146508, -0.18079112,  0.33788483,
       -0.13103164, -0.80837311,  0.20052902,  0.73023462,  0.9970574 ])

In [15]:
np.random.randint(6)

5

In [16]:
np.random.randint(1,100,7)#low ,high ,value 

array([59, 54, 73,  2, 29, 96, 97], dtype=int32)

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
arr.mean()

np.float64(5.0)

In [26]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [27]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [28]:
arr.std()


np.float64(2.581988897471611)

In [29]:
arr.argmax()

np.int64(8)

In [30]:
arr.argmin()

np.int64(0)

In [31]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr=arr.reshape(6,5)

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
arr[9]

np.int64(20)

In [41]:
arr[2:1]

array([], dtype=int64)

In [42]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [43]:
arr.shape

(6, 5)

In [44]:
arr[0]

array([1, 2, 3, 4, 5])

In [45]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [53]:
arr[0:6,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

In [54]:
arr=np.arange(11,21)

In [55]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
bool_index=arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [64]:
arr=arr[bool_index]

In [65]:
arr

array([12, 14, 16, 18, 20])

In [66]:
a1=np.arange(1,6)
a2=np.arange(6,11)

In [67]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [68]:
a1-a2

array([-5, -5, -5, -5, -5])

In [69]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [70]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [71]:
a1//a2

array([0, 0, 0, 0, 0])

In [72]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [73]:
l=[1,2,3,4,5]
arr=np.array(l)
arr


array([1, 2, 3, 4, 5])

In [74]:
arr+10

array([11, 12, 13, 14, 15])

In [75]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
arr2*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [77]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
a=np.arange(10,31)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [80]:
a[:10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [81]:
a*15

array([150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330,
       345, 360, 375, 390, 405, 420, 435, 450])

In [82]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [83]:
b=a

In [84]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [87]:
b[0]=100
b
a

array([100,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [88]:
a

array([100,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [89]:
b=a.copy()
b

array([100,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [90]:
a

array([100,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [91]:
b[0]=1

In [92]:
b


array([ 1, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [93]:
a

array([100,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [95]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[10,11,12],[13,14,15],[16,17,18]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [97]:
A*B


array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [98]:
A@B

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [99]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
B.T

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [101]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [103]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10]) 
   

In [104]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

exercises


In [109]:
s=np.arange(1,82).reshape(9,9)

In [110]:
s.sum()

np.int64(3321)

In [111]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [120]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("Not a valid sudoku")
else:
    print("Valid sudoku")   

Valid sudoku


In [121]:
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("Not a valid sudoku")
else:
    print("Valid sudoku")  

Valid sudoku


In [124]:
slicing=s[0:3,0:3]
slicing

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [126]:
slicing=s[0:3,3:6]
slicing

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [127]:
slicing=s[3:6,3:6]
slicing

array([[7, 6, 1],
       [8, 5, 3],
       [9, 2, 4]])

In [129]:
for i in range(0,9,3):
    for j in range(0,9,3):
        slicing=s[i:i+3,j:j+3]
        slicing.sum()
        print(slicing.sum())

45
45
45
45
45
45
45
45
45


In [130]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [132]:
data.shape

(5, 3)

In [136]:
age_mean=print(data[0:5,0:1])

[[18]
 [19]
 [17]
 [18]
 [20]]


In [140]:
np.mean(data[0:5,0:1])

np.float64(18.4)

In [146]:
np.mean(data[:,0])

np.float64(18.4)

In [144]:
age_mean=print(data[0:5,1:2])


[[85]
 [92]
 [76]
 [65]
 [90]]


In [145]:
data[:,1]

array([85, 92, 76, 65, 90])

In [148]:
np.max(data[:,2])

np.int64(95)

In [149]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [168]:

#Increase Math marks of all students by 5.
data[:,1]+=5
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [167]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [173]:

#Find how many students are younger than 19.
data[data[:,0]<19]


array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [174]:

#Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,0]), np.mean(data[:,1]), np.mean(data[:,2])

(np.float64(18.4), np.float64(86.6), np.float64(83.2))

In [175]:

#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [176]:

#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])