In [2]:
%pip install numpy


  Using cached numpy-2.4.4-cp313-cp313t-win_amd64.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 2.0 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.5 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.5 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.5 MB 2.6 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.5 MB 2.4 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.5 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.5 MB 2.3 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.5 MB 2.4 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.5 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.5 MB 2.6 MB/s eta 0:00:03
   ---------------

In [2]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

In [5]:
arr=np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a=[1,2,3,4,4.5,'hello']
a

[1, 2, 3, 4, 4.5, 'hello']

In [8]:
np.array(a)

array(['1', '2', '3', '4', '4.5', 'hello'], dtype='<U32')

In [9]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr=np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.random.rand(5)

array([0.022132  , 0.9078924 , 0.84171394, 0.46094411, 0.19925639])

In [34]:
np.random.randn(10)

array([-0.00615395, -0.88718682, -1.25414818,  0.51990749,  1.16313847,
        1.04470738,  1.81624418,  1.44881429,  2.12568472, -0.59193917])

In [36]:
np.random.randint(6)

2

In [ ]:
np.random.randint(1,100,7)#low ,high ,value 

array([57, 51, 33, 63,  1, 92, 95], dtype=int32)

In [50]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.shape

(3, 3)

In [52]:
arr.size

9

In [42]:
arr.dtype

dtype('int64')

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max()

np.int64(9)

In [48]:
arr.sum()

np.int64(45)

In [49]:
arr.mean()

np.float64(5.0)

In [55]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [57]:
arr.std()


np.float64(2.581988897471611)

In [58]:
arr.argmax()

np.int64(8)

In [59]:
arr.argmin()

np.int64(0)

In [62]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr=arr.reshape(6,5)

In [66]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])